$(document).ready(function(){
  $(window).scroll(function(){
    if($(this).scrollTop()>1){
      $(".hide").addClass("add");
      $(".hide").css("transition","1s");
      $(".main").fadeIn();
      $(".narrow").fadeOut();

    }
    else{
      $(".hide").removeClass("add");
      $(".hide").css("transition","0.4s");
      $(".main").fadeOut();
      $(".narrow").fadeIn();
    }
  });
});
$(document).ready(function(){
  $(window).scroll(function(){
    if($(this).scrollTop()>1){
      $(".special").addClass("transform");
      $(".special").css("transition","1s");

    }
    else{
      $(".special").removeClass("transform");
      $(".special").css("transition","1s");
    }
  });
});
$(document).ready(function(){
  $(window).scroll(function(){
    if($(this).scrollTop()>169){
      $(".con").fadeIn();

    }
    else{
      $(".con").fadeOut();
    }
  });
});